site_name: ITS Ontology - Traffic Regulations
site_description: A registry for documenting the ontology of traffic regulation concepts
repo_url: https://github.com/ISO-TC204/ontology-its-regulation
nav:
- Home: index.md
- Condition Pattern:
  - Condition Pattern Overview: classes/ConditionPattern.md
  - Classes:
    - Access Category Code: classes/AccessCategoryCode.md
    - Access Condition: classes/AccessCondition.md
    - Condition: classes/Condition.md
    - Condition Set: classes/ConditionSet.md
    - Destination Info: classes/DestinationInfo.md
    - Legal Basis: classes/LegalBasis.md
    - Location Condition: classes/LocationCondition.md
    - Logical Operator Code: classes/LogicalOperatorCode.md
    - Non Vehicular Road User Code: classes/NonVehicularRoadUserCode.md
    - Non Vehicular Road User Condition: classes/NonVehicularRoadUserCondition.md
    - Permit Information: classes/PermitInformation.md
    - Permit Type Code: classes/PermitTypeCode.md
    - Required Permit Condition: classes/RequiredPermitCondition.md
    - Road Condition: classes/RoadCondition.md
    - Road Type Code: classes/RoadTypeCode.md
    - Sign Destination: classes/SignDestination.md
    - Standing Or Parking Category Code: classes/StandingOrParkingCategoryCode.md
    - Standing Or Parking Condition: classes/StandingOrParkingCondition.md
    - Text Composite: classes/TextComposite.md
    - Tunnel Category Code: classes/TunnelCategoryCode.md
    - Tunnel Category Condition: classes/TunnelCategoryCondition.md
    - Vehicle Characteristic: classes/VehicleCharacteristic.md
    - Vehicle Characteristic Condition: classes/VehicleCharacteristicCondition.md
    - Versioned Condition: classes/VersionedCondition.md
    - Versioned Permit Characteristics: classes/VersionedPermitCharacteristics.md
    - Versioned Thing: classes/VersionedThing.md
    - Weather Condition: classes/WeatherCondition.md
    - Weather Condition Code: classes/WeatherConditionCode.md
  - Properties:
    - applicableLocation: properties/applicableLocation.md
    - arrowDirection: properties/arrowDirection.md
    - destinationHorizon: properties/destinationHorizon.md
    - destinationPlace: properties/destinationPlace.md
    - destinationRoad: properties/destinationRoad.md
    - displayType: properties/displayType.md
    - divergeHorizon: properties/divergeHorizon.md
    - divergeName: properties/divergeName.md
    - divergeRoute: properties/divergeRoute.md
    - forAccessCategory: properties/forAccessCategory.md
    - forNonVehicularRoadUserType: properties/forNonVehicularRoadUserType.md
    - forPermitType: properties/forPermitType.md
    - forRoadType: properties/forRoadType.md
    - forStandingOrParkingCategory: properties/forStandingOrParkingCategory.md
    - forTunnelCategory: properties/forTunnelCategory.md
    - forWeatherConditionType: properties/forWeatherConditionType.md
    - grantsPermission: properties/grantsPermission.md
    - hasAssociatedFee: properties/hasAssociatedFee.md
    - hasCondition: properties/hasCondition.md
    - hasContactInformation: properties/hasContactInformation.md
    - hasIssuingAuthority: properties/hasIssuingAuthority.md
    - hasLegalBasis: properties/hasLegalBasis.md
    - hasRegistrationMachine: properties/hasRegistrationMachine.md
    - hasVersionedPermitCharacteristics: properties/hasVersionedPermitCharacteristics.md
    - howToObtainPermit: properties/howToObtainPermit.md
    - implementedLocation: properties/implementedLocation.md
    - isActive: properties/isActive.md
    - isLocationSpecific: properties/isLocationSpecific.md
    - legalBasis: properties/legalBasis.md
    - locationByOrder: properties/locationByOrder.md
    - logicalOperator: properties/logicalOperator.md
    - maximumDurationOfPermit: properties/maximumDurationOfPermit.md
    - minimumTimeToNextEntry: properties/minimumTimeToNextEntry.md
    - otherAccessRestriction: properties/otherAccessRestriction.md
    - permitCondition: properties/permitCondition.md
    - permitInformation: properties/permitInformation.md
    - permittedEntityType: properties/permittedEntityType.md
    - trafficImpactLocation: properties/trafficImpactLocation.md
    - urlForApplication: properties/urlForApplication.md
    - urlForInformation: properties/urlForInformation.md
- Core Pattern:
  - Core Pattern Overview: classes/CorePattern.md
  - Classes:
    - Regulation Thing: classes/RegulationThing.md
  - Properties:
    - RegulationDataProperty: properties/RegulationDataProperty.md
    - RegulationObjectProperty: properties/RegulationObjectProperty.md
- Regulation Pattern:
  - Regulation Pattern Overview: classes/TrafficRegulationPattern.md
  - Classes:
    - Implementation Status Code: classes/ImplementationStatusCode.md
    - Reason Code: classes/ReasonCode.md
    - Regulatory Scope Code: classes/RegulatoryScopeCode.md
    - Rule Maker Role: classes/RuleMakerRole.md
    - Traffic Regulation: classes/TrafficRegulation.md
    - Traffic Regulation Order: classes/TrafficRegulationOrder.md
    - Type Of Regulation: classes/TypeOfRegulation.md
  - Properties:
    - associatedTrafficControlDevice: properties/associatedTrafficControlDevice.md
    - authorizingTrafficRegulation: properties/authorizingTrafficRegulation.md
    - hasDetails: properties/hasDetails.md
    - implementationStatus: properties/implementationStatus.md
    - implementedLocation: properties/implementedLocation.md
    - implementedValidity: properties/implementedValidity.md
    - issuedTro: properties/issuedTro.md
    - issuingAuthority: properties/issuingAuthority.md
    - locationByOrder: properties/locationByOrder.md
    - memberTrafficRegulation: properties/memberTrafficRegulation.md
    - reasonCode: properties/reasonCode.md
    - regulatoryScope: properties/regulatoryScope.md
    - validityByOrder: properties/validityByOrder.md
- Traffic Control Device Pattern:
  - Traffic Control Device Pattern Overview: classes/TrafficControlDevicePattern.md
  - Classes:
    - Access Control Device: classes/AccessControlDevice.md
    - Access Control Type Code: classes/AccessControlTypeCode.md
    - Channelization Device: classes/ChannelizationDevice.md
    - Channelization Type Code: classes/ChannelizationTypeCode.md
    - Composite Sign: classes/CompositeSign.md
    - International Sign: classes/InternationalSign.md
    - Pavement Marking: classes/PavementMarking.md
    - Pavement Marking Type Code: classes/PavementMarkingTypeCode.md
    - Road Surface Feature: classes/RoadSurfaceFeature.md
    - Road Surface Feature Type Code: classes/RoadSurfaceFeatureTypeCode.md
    - Simple Sign: classes/SimpleSign.md
    - Traffic Control Device: classes/TrafficControlDevice.md
    - Traffic Signal: classes/TrafficSignal.md
    - Traffic Signal Device: classes/TrafficSignalDevice.md
    - Warning Beacon: classes/WarningBeacon.md
  - Properties:
    - accessControlType: properties/accessControlType.md
    - channelizationType: properties/channelizationType.md
    - image: properties/image.md
    - nationalSignId: properties/nationalSignId.md
    - pavementMarkingType: properties/pavementMarkingType.md
    - pictogram: properties/pictogram.md
    - roadSurfaceFeatureType: properties/roadSurfaceFeatureType.md
    - simpleSignList: properties/simpleSignList.md
    - url: properties/url.md
site_url: https://github.com/ISO-TC204/ontology-its-regulation
copyright: <p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/">
  <a href="https://creativecommons.org/licenses/by/4.0/?ref=chooser-v1" target="_blank"
  rel="license noopener noreferrer" style="display:inline-block;">CC BY 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;"
  src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img
  style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1"
  alt=""></a></p>
theme:
  name: material
  features:
  - content.code.copy
  - content.status
  - content.tooltips
  - icons
  - navigation.path
  - navigation.top
  icon:
    repo: fontawesome/brands/github
    admonition:
      question: fontawesome/solid/comments
  palette:
  - scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
extra_css:
- stylesheets/extra.css
extra_javascript:
- https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
- javascripts/tablesort.js
plugins:
- search
- git-revision-date-localized:
    type: date
markdown_extensions:
- abbr
- admonition
- attr_list
- def_list
- md_in_html
- meta
- footnotes
- pymdownx.blocks.caption
- pymdownx.details
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
    use_pygments: true
- pymdownx.inlinehilite
- pymdownx.snippets:
    base_path: docs
    check_paths: true
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: ''
- pymdownx.tabbed:
    alternate_style: true
- toc:
    permalink: true
extra:
  search:
    highlight: true
  hide:
  - title
  version:
    provider: mike
    alias: true
    default: latest
